theme: jekyll-theme-minimal
title: Aniket Soni # your name (or website title) here
logo: "https://drive.google.com/uc?export=view&id=1y_4-ikbfKh_U_8Jx99lBruIjffUF0N7G" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Associate - Projects @Cognizant | 2x GCP Certified | Databricks Certified Data Engineer Associate | IAF Young Achievers' Awardee | Full-Stack Engineer | Judge | Speaker | Tech Mentor | Tech Reviewer
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/aniketsoni/">LinkedIn</a>
  <br>
  <br>
